version: 2

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable-all: false
  enable:
    # Enabled by default
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional linters
    - misspell
    - revive
    - unconvert
    - unparam
    - goconst
    - gocyclo
    - dupl
    - gosec

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true

  gocyclo:
    min-complexity: 15

  revive:
    confidence: 0.8

  misspell:
    locale: US

  dupl:
    threshold: 100

  gosec:
    excludes:
      - G404

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-dirs:
    - vendor
    - fo-dicom-code
    - tools

  exclude-files:
    - ".*_generated\\.go$"
    - ".*_test\\.go$"

  exclude-rules:
    - path: _test\.go
      linters:
        - revive
        - gocyclo
        - dupl
        - gosec
        - errcheck
      text: "dot imports"

    - path: .*_generated\.go
      linters:
        - gocyclo
        - dupl
        - goconst

    # Exclude errcheck from examples (示例代码可以省略错误检查)
    - path: (examples|cmd)/
      linters:
        - errcheck
        - gosec

    # Exclude dupl from all files (代码重复检查太严格)
    - linters:
        - dupl

output:
  formats:
    colored-line-number:
      path: stdout
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
