run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # 检查未处理的错误
    - gosimple      # 简化代码建议
    - govet         # Go vet 检查
    - ineffassign   # 检测无效的赋值
    - staticcheck   # 静态分析
    - unused        # 检查未使用的代码
    - gofmt         # 检查代码格式
    - goimports     # 检查 import 顺序
    - misspell      # 拼写检查
    - revive        # 快速的 Go linter
    - typecheck     # 类型检查
    - unconvert     # 不必要的类型转换
    - unparam       # 未使用的函数参数
    - goconst       # 重复的常量字符串
    - gocyclo       # 圈复杂度
    - dupl          # 重复代码检测

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  gocyclo:
    min-complexity: 15

  govet:
    check-shadowing: true

  revive:
    confidence: 0.8

  misspell:
    locale: US

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # 允许在测试文件中使用 dot imports
    - path: _test\.go
      linters:
        - revive
      text: "dot imports"

    # 允许在生成的代码中有长行
    - path: generated
      linters:
        - lll

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
