run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code suggestions
    - govet         # Go vet checks (includes shadow checking)
    - ineffassign   # Detect ineffective assignments
    - staticcheck   # Static analysis
    - unused        # Check for unused code
    - gofmt         # Check code formatting
    - goimports     # Check import order
    - misspell      # Spell checking
    - revive        # Fast Go linter
    - typecheck     # Type checking
    - unconvert     # Unnecessary type conversions
    - unparam       # Unused function parameters
    - goconst       # Repeated constant strings
    - gocyclo       # Cyclomatic complexity
    - dupl          # Duplicate code detection
    - gosec         # Security issues

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable:
      - shadow

  gocyclo:
    min-complexity: 15

  revive:
    confidence: 0.8

  misspell:
    locale: US

  dupl:
    threshold: 100

  gosec:
    excludes:
      - G404 # Use of weak random number generator - acceptable for non-crypto use

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-dirs:
    - vendor
    - fo-dicom-code

  exclude-files:
    - ".*_generated\\.go$"

  exclude-rules:
    # Allow dot imports in test files
    - path: _test\.go
      linters:
        - revive
      text: "dot imports"

    # Allow long lines in generated code
    - path: generated
      linters:
        - lll

    # Exclude some linters from running on test files
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - gosec

    # Allow complexity in generated files
    - path: .*_generated\.go
      linters:
        - gocyclo
        - dupl
        - goconst

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
